name: countries_app
description: A Countries App using Clean Architecture
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # State Management
  flutter_bloc: ^8.1.3
  # Network
  dio: ^5.4.0
  # Dependency Injection
  get_it: ^7.6.7
  # Functional Programming
  dartz: ^0.10.1
  # Equatable for value comparison
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true 